services:
  - docker

install:
  - docker build -t ddiez/samtools .

script:
  - docker run ddiez/samtools

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

      # push latest.
      docker push ddiez/samtools;

      # tag and push.
      VERSION=`docker run ddiez/samtools printenv VERSION`;
      docker tag ddiez/samtools ddiez/samtools:$VERSION;
      docker push ddiez/samtools:$VERSION;
    fi
